### ISSUE TITLE
[Question] I can make non-blocking scope?

### ISSUE THREAD

**Issue by y-ich** [Kimundi/scoped_thread_pool_cache#18]
Hi.

I want to let a main thread work during scoped multithreading like the following pseudo-code.

    fn example() {
       let mut pool = Pool::new(4);
        let scope = pool.non_block_scoped(|scoped| { ... });
        do_something();
        scope.join_all();
    }

Is it possible on your scoped-threadpool?

**Comment by Kimundi** [comment]
Not with that API. The `pool.scoped()` has to be a blocking function call for safety reasons, since a RAII guard could be leaked, which would cause memory unsafety.

You should be able to do other work in the outer closure though:

```rust
pool.scoped(|scope| {
    scope.execute(move || {
        // ...            
    });
    do_something();
    scope.execute(move || {
        // ...            
    });
});
```

**Comment by y-ich** [comment]
Great!
I have never considered about it.
Thank you!
