### ISSUE TITLE
Make the library safe again once the compiler bugfix travelled through the release train

### ISSUE THREAD

**Issue by Kimundi** [Kimundi/scoped_thread_pool_cache#4]

**Comment by TimNN** [comment]
I think this can happen now that 1.4 has been released (which appears to be the required version if I interpret `build.rs` correctly).

**Comment by fschutt** [comment]
Is this fixed? Is the library safe to use, does it leak memory? Just asking.

**Comment by Kimundi** [comment]
Oh, seems I never closed this - the library has safe API for quite some time again, and should also not leak memory.
